# Configuration for the policy extraction and clustering pipeline

# File paths
paths:
  data_dir: "data"          # Directory for input data
  output_dir: "output"      # Directory for results and visualizations
  model_dir: "models"       # Directory for saved models

# Model configurations
models:
  # Policy extraction model (fine-tuned for regulatory text analysis)
  policy_extractor: "JohnSnowLabs/spark-nlp/classifierdl_bertwikiner_policy"
  
  # Impact classification model (optimized for policy sentiment)
  impact_classifier: "distilbert-base-uncased-finetuned-sentiment"
  
  # Sentence embedding model for clustering
  semantic_model: "sentence-transformers/all-mpnet-base-v2"

# Processing parameters
parameters:
  # Extraction parameters
  min_sentence_length: 5
  policy_confidence_threshold: 0.3
  
  # Clustering parameters
  max_clusters: 30  # Increased for larger datasets
  min_cluster_size: 3  # Smaller minimum for finer granularity
  clustering_method: "hierarchical"  # Options: "hierarchical", "kmeans", "dbscan"

# Policy extraction configuration
extraction:
  # Expanded list of policy-related keywords (sector-specific additions)
  policy_keywords:
    - policy
    - regulation
    - legislation
    - law
    - rule
    - guideline
    - framework
    - program
    - initiative
    - strategy
    - plan
    - measure
    - intervention
    - mechanism
    - instrument
    - proposal
    - recommendation
    - action
    - mandate
    - compliance
    - governance
    - directive
    - statute
    - ordinance
    - protocol
    - enforcement
    - oversight

  # Syntactic patterns suggesting policy statements
  policy_patterns:
    - "MODAL VERB + ACTION VERB + OBJECT"
    - "RECOMMEND THAT SUBJECT VERB"
    - "SUGGEST IMPLEMENTATION OF X"
    - "PROPOSE NEW REGULATION ON X"
    - "POLICY SHOULD ADDRESS X"
    - "MANDATE ACTION TO ACHIEVE X"

# Impact classification configuration
impact:
  # Expanded list of impact-related keywords
  positive_keywords:
    - improve
    - increase
    - enhance
    - strengthen
    - promote
    - foster
    - advance
    - sustainable
    - resilient
    - efficient
    - equitable
    - beneficial
    - encourage

  negative_keywords:
    - reduce
    - decrease
    - limit
    - restrict
    - negative
    - harmful
    - adverse
    - costly
    - inefficient
    - controversial
    - exacerbate
    - burden

# Visualization settings
visualization:
  # Color scheme for plots
  colors:
    positive: "#2ecc71"
    neutral: "#3498db"
    negative: "#e74c3c"
    unknown: "#95a5a6"
    
  # Number of representative examples per cluster
  n_examples: 5  # Increased for better interpretability

  # Additional plot options
  plot_types:
    - "bar"
    - "scatter"
    - "heatmap"
    - "network"
